// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4SQkrNsDXJcfK16jElDKkHjdzrrB6zsQ',
    appId: '1:536676396267:web:05a8f915cb2ec7a39aa2ae',
    messagingSenderId: '536676396267',
    projectId: 'casamentobuerba',
    authDomain: 'casamentobuerba.firebaseapp.com',
    storageBucket: 'casamentobuerba.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMiYkfwHyKsiaL_L1QVTegXOZXSGWzC5I',
    appId: '1:536676396267:android:6fc3f5da9be675549aa2ae',
    messagingSenderId: '536676396267',
    projectId: 'casamentobuerba',
    storageBucket: 'casamentobuerba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzSU3OC4rtG4DPywT0Yd2niLMiyTyT9XQ',
    appId: '1:536676396267:ios:19a20296b3e5c9bc9aa2ae',
    messagingSenderId: '536676396267',
    projectId: 'casamentobuerba',
    storageBucket: 'casamentobuerba.firebasestorage.app',
    iosBundleId: 'com.example.presentesCasamento',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzSU3OC4rtG4DPywT0Yd2niLMiyTyT9XQ',
    appId: '1:536676396267:ios:19a20296b3e5c9bc9aa2ae',
    messagingSenderId: '536676396267',
    projectId: 'casamentobuerba',
    storageBucket: 'casamentobuerba.firebasestorage.app',
    iosBundleId: 'com.example.presentesCasamento',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4SQkrNsDXJcfK16jElDKkHjdzrrB6zsQ',
    appId: '1:536676396267:web:33d0ca74ed31cb8a9aa2ae',
    messagingSenderId: '536676396267',
    projectId: 'casamentobuerba',
    authDomain: 'casamentobuerba.firebaseapp.com',
    storageBucket: 'casamentobuerba.firebasestorage.app',
  );
}
